// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFNJkwh5LtXLOsFw499NfBoVhom07PN4',
    appId: '1:271956599540:web:c14c96d767e545650af4a1',
    messagingSenderId: '271956599540',
    projectId: 'flutter-ai-playground-c654f',
    authDomain: 'flutter-ai-playground-c654f.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-c654f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOspKYRUUehOoEuz41NPtsDZDiE4UqxHg',
    appId: '1:271956599540:android:c95548fc4da5d48c0af4a1',
    messagingSenderId: '271956599540',
    projectId: 'flutter-ai-playground-c654f',
    storageBucket: 'flutter-ai-playground-c654f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLQwTp7BgKYidQEj5CTVeq-pJ6tz65lo',
    appId: '1:271956599540:ios:a225097327a6139b0af4a1',
    messagingSenderId: '271956599540',
    projectId: 'flutter-ai-playground-c654f',
    storageBucket: 'flutter-ai-playground-c654f.firebasestorage.app',
    iosBundleId: 'com.example.carsflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLQwTp7BgKYidQEj5CTVeq-pJ6tz65lo',
    appId: '1:271956599540:ios:a225097327a6139b0af4a1',
    messagingSenderId: '271956599540',
    projectId: 'flutter-ai-playground-c654f',
    storageBucket: 'flutter-ai-playground-c654f.firebasestorage.app',
    iosBundleId: 'com.example.carsflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFNJkwh5LtXLOsFw499NfBoVhom07PN4',
    appId: '1:271956599540:web:a387d580b20442c70af4a1',
    messagingSenderId: '271956599540',
    projectId: 'flutter-ai-playground-c654f',
    authDomain: 'flutter-ai-playground-c654f.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-c654f.firebasestorage.app',
  );
}
